### ISSUE TITLE
Exception when running example code

### ISSUE THREAD

**Issue by bencardoen** [natekupp/ffx#30] opened 2017-11-21 03:29 UTC
Hi, 

When I execute the example code from the readme I get the following exception:

```
~/.local/lib/python3.5/site-packages/ffx/core.py in _pathwiseLearn(self, ss, varnames, bases, X_orig, X_orig_regress, y_orig, max_num_bases, target_nmse, verbose, **fit_params)
    863         st, fin = numpy.log10(alpha_max * ss.eps()), numpy.log10(alpha_max)
    864         alphas1 = numpy.logspace(
--> 865             st, fin, num=ss.numAlphas() * 10)[::-1][:ss.numAlphas() / 4]
    866         alphas2 = numpy.logspace(st, fin, num=ss.numAlphas())
    867         alphas = sorted(set(alphas1).union(alphas2), reverse=True)

TypeError: slice indices must be integers or None or have an __index__ method
```

This is on Python3.5

Any idea what's the issue here ?

Thanks,

Ben

**Comment by jmmcd** [comment] 2017-11-21 17:27
Duplicate of #25.

**Closed by jmmcd** 2017-11-21 17:27 UTC
